# Generated by Django 4.2.23 on 2025-11-19 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='interviewer.interviewsession')),
            ],
        ),
    ]
